### ISSUE TITLE
數據更新

### ISSUE THREAD

**Issue by prplchry** [covid19-eu-zh/docs#10]
ECDC 表格更新在 Google Sheet page 3

**Comment by cmp0xff** [comment]
@prplchry 描述不清。

**Comment by prplchry** [comment]
ECDC 表格更新在 Google Sheet page 3

**Comment by cmp0xff** [comment]
@Lemange 整理的
> ![grafik](https://user-images.githubusercontent.com/5564164/75582394-c1f0b680-5a6b-11ea-866e-da114663b67e.png)

@cmp0xff 想问一下 @Lemange 这个数据来源是不是也得写一下

**Comment by prplchry** [comment]
更新RKI數據表格（10點發佈的德國各州感染人數統計）于 [Google Drive](https://docs.google.com/spreadsheets/d/1EElAWqvZSV8rr6vjo7AkxY5zfirNtVif-JD2D9X-iI0/edit#gid=1370359988) page 3

**Comment by prplchry** [comment]
ECDC 數據更新，于 [Google Drive ](https://docs.google.com/spreadsheets/d/1EElAWqvZSV8rr6vjo7AkxY5zfirNtVif-JD2D9X-iI0/edit#gid=1370359988) page 3。

**Comment by ZequnZ** [comment]
请问一下这些数据的数据源是什么？整理方式又是什么呢？

**Comment by prplchry** [comment]
@ZequnZ 数据来源：

ECDC表格與圖表：https://www.ecdc.europa.eu/en/cases-2019-ncov-eueea
WHO報告：https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/
RKI：https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

整理方式：
复制粘贴以及汉化

**Comment by prplchry** [comment]
WHO29日数据更新：https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200229-sitrep-40-covid-19.pdf?sfvrsn=7203e653_2 （表格等无法粘贴，改存pdf链接）

**Comment by prplchry** [comment]
WHO29日数据更新：https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200229-sitrep-40-covid-19.pdf?sfvrsn=7203e653_2 （表格等无法粘贴，改存pdf链接）

**Comment by prplchry** [comment]
ECDC与RKI數據更新，于 [Google Drive](https://docs.google.com/spreadsheets/d/1EElAWqvZSV8rr6vjo7AkxY5zfirNtVif-JD2D9X-iI0/edit#gid=1370359988) page 3。

**Comment by prplchry** [comment]
ECDC与RKI數據更新，于 Google Drive page 3。

**Comment by prplchry** [comment]
RKI 15：00更新数据，于 [Google Drive ](https://docs.google.com/spreadsheets/d/1EElAWqvZSV8rr6vjo7AkxY5zfirNtVif-JD2D9X-iI0/edit#gid=1370359988) page 3。

**Comment by cmp0xff** [comment]
@prplchry 我開了個新表格處理 RKI.de 上的德國數據。可以交給我了。

**Comment by prplchry** [comment]
@cmp0xff 好，前幾日有需要可以拷貝過去

**Comment by prplchry** [comment]
ECDC 數據見于 [Google Sheet](https://docs.google.com/spreadsheets/d/1EElAWqvZSV8rr6vjo7AkxY5zfirNtVif-JD2D9X-iI0/edit#gid=1370359988) page 3。
WHO 形勢報告鏈接：https://www.who.int/docs/default-source/coronaviruse/20200302-sitrep-42-covid-19.pdf?sfvrsn=d863e045_2

**Comment by prplchry** [comment]
RKI 数据更已新（目前channel 每天发布15点的数据，所以我还是会复制到Sheet 先）@cmp0xff

**Comment by cmp0xff** [comment]
RKI 數據可以放心交給我處理，圖都畫好了。@prplchry 可以省力做別的。

**Comment by cmp0xff** [comment]
> RKI 數據可以放心交給我處理，圖都畫好了。@prplchry 可以省力做別的。

德國跟奧地利的數據可以自動爬了，見[新倉庫](https://github.com/covid19-eu-zh/covid19-eu-data/tree/master/dataset) 以後不用手工收集了。
