### ISSUE TITLE
展会可能取消

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/docs#12]
@Ellensberg 

> Current information from the ITB Berlin Exhibition Management:

> Messe Berlin GmbH is currently coordinating with the public authorities at federal and state level on how to proceed with regard to ITB Berlin 2020 and COVID-19. It is expected that more detailed information will be available in the evening of 28 February 2020 at the earliest. We will inform you as soon as we have new information.

> Der Veranstalter, die Messe Berlin, will bis Freitagabend bekanntgeben, ob er die ITB mit rund 10 000 Ausstellern aus aller Welt vom 4. bis 8. März durchzieht.

> hhh，就是这个展会特别大
> 可以说是一个风向标。。它取消了

@prplchry 

> 瑞士那个也可以一起 1000以上人参加的大活动全部取消
> http://www.spiegel.de/wirtschaft/soziales/coronavirus-schweiz-verbietet-veranstaltungen-mit-mehr-als-1000-menschen-a-86803b45-0708-4a54-9530-0163ca11388b-amp

**Comment by Ellensberg** [comment]
@cmp0xff ITB Berlin 2020 will not take place.

**Comment by cmp0xff** [comment]
@Ellensberg 写完之后可以 close 这个 issue，练习一下

**Comment by Ellensberg** [comment]
@cmp0xff 是不是如果直接在tele里面comment，只有我当前comment的内容，但是在github里评论，就可以收到这个issue的所有更新？比如这个，只有一条
