### ISSUE TITLE
热线电话

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/docs#13]
lans:

> 不知道这个有没有价值，日本驻杜塞大使馆整理的一些[热线电话](https://www.de.emb-japan.go.jp/itpr_ja/konsular_coronahotline200228.html)

@cmp0xff 
> 之前地德国相关电话汇总
> https://t.me/covid19_eu_zh_c/17
> https://t.me/covid19_eu_zh_c/19
> https://t.me/covid19_eu_zh_c/33
> [驻德国臺北代表处](https://www.roc-taiwan.org/de/post/2435.html)
> 電話：+49-30-2036 10
> 傳真：+49-30-2036 1101
> 急難救助行動電話：+49-171 389 8257

需要**法国意大利西班牙葡萄牙**电话汇总，至少包含陆臺

**Comment by cmp0xff** [comment]
@Ulyssssss 

> #意大利 #Italia 紧急救护电话118
> 新馆病毒疑似病例报告电话112
> 新型冠状病毒咨询专线1500（支持中、意、英文）
> 驻意大利使馆领保应急电话：0039-3939110852
> 驻米兰总领馆领保应急电话：0039-3272862927
> 驻佛罗伦萨总领馆领保应急电话：0039-3357748753
> 外交部全球领保与应急呼叫中心电话：0086-10-12308
> 各大区应急电话请查询[卫生部网站](http://www.salute.gov.it/portale/news/p3_2_1_1_1.jsp?lingua=italiano&menu=notizie&p=dalministero&id=4104)

**Comment by cmp0xff** [comment]
@cyannn 
> 冠*
> 以及文字和數字中間最好空一格

**Comment by ZequnZ** [comment]
在某个微信群看到的信息。经本人查证，为真实有效信息。如有帮助，请采纳。

```
德国冠状病毒热线电话（Coronavirus-Hotline）:

030-9028 2828（柏林）

040-428 284 000（汉堡）

09131-6808 5101（巴伐利亚州）

0800-5554666（黑森州）

0211-8554774（北威州）

0800-5758100（莱法州）

0711-90439555（巴符州）

0681-5014422（萨尔州）

0800 8484 111（全德）

急救电话：112，紧急医疗服务专线：116117
```

**Comment by cmp0xff** [comment]
> 在某个微信群看到的信息。经本人查证，为真实有效信息。如有帮助，请采纳。
> 德国冠状病毒热线电话（Coronavirus-Hotline）:
> 
> 030-9028 2828（柏林）
> 
> 040-428 284 000（汉堡）
> 
> 09131-6808 5101（巴伐利亚州）
> 
> 0800-5554666（黑森州）
> 
> 0211-8554774（北威州）
> 
> 0800-5758100（莱法州）
> 
> 0711-90439555（巴符州）
> 
> 0681-5014422（萨尔州）
> 
> 0800 8484 111（全德）
> 
> 急救电话：112，紧急医疗服务专线：116117

感谢帮助。如您所见，我们在前面可能也已经整理了部分此类信息，见
https://t.me/covid19_eu_zh_c/17
特别是那个所谓全德电话，其实似乎是由一家保险公司提供的。我们希望希望拨打之前知道一点对方是谁在接电话。

我们的目标是所有消息来源都可查证并直接列举在消息上。所以直接贴电话并表示“我们查证过”或“有人查证过”是不够的。

由于任务多人手少，目前还没有人做这个查证工作。另外也希望把所有的陆+台外事机构相关电话都贴上。目前这个整理还远远没有完成。

如果可以的话，我们希望至少先做完德国（编辑比较多），再逐步扩展到其他欧盟国家。如果您有兴趣提供相关信息，我们非常感谢。
