### ISSUE TITLE
弄一个新台标

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/docs#14]
@cyan 
> 我一直想問 你們覺得弄一個新台標如何？
> 雖然我不會設計 但可以問問學設計的朋友 不知道各位有沒有什麼想法

@Ulyssssss 
> 赞成

Y 
> 早就想了

@cmp0xff
> 我希望去「國」存「文」

@wxfbeing 
> 👍

**Comment by cmp0xff** [comment]
@cyannn 
> 各位對臺標有沒有什麼想法？
> 什麼樣的風格/哪些元素/精神之類的

**Comment by cmp0xff** [comment]
@neoatlantis 
> 我们把台标换成瘟疫公司里顶上那个新闻logo吧？😂

**Comment by neoatlantis** [comment]
我的提案：

![logo svg](https://user-images.githubusercontent.com/2693447/75589874-44817200-5a7c-11ea-87e8-ae3bb3751f5b.png)

![logo-sw-long](https://user-images.githubusercontent.com/2693447/75589879-464b3580-5a7c-11ea-838b-5fcd77c6a6cd.png)

![logo-p2](https://user-images.githubusercontent.com/2693447/75589878-45b29f00-5a7c-11ea-9c80-a6f91855a674.png)

![logo3 svg](https://user-images.githubusercontent.com/2693447/75589876-45b29f00-5a7c-11ea-9858-d35acae88653.png)

**Comment by prplchry** [comment]
> 我的提案：
> 
> ![logo svg](https://user-images.githubusercontent.com/2693447/75589874-44817200-5a7c-11ea-87e8-ae3bb3751f5b.png)
> 
> ![logo-sw-long](https://user-images.githubusercontent.com/2693447/75589879-464b3580-5a7c-11ea-838b-5fcd77c6a6cd.png)
> 
> ![logo-p2](https://user-images.githubusercontent.com/2693447/75589878-45b29f00-5a7c-11ea-9c80-a6f91855a674.png)
> 
> ![logo3 svg](https://user-images.githubusercontent.com/2693447/75589876-45b29f00-5a7c-11ea-9858-d35acae88653.png)

logo 3 很棒啊！機械感會抵消一些對病毒形狀的恐懼

**Comment by wxfbeing** [comment]
![109C9B15-9734-4A5E-8693-044F7FAE8F17](https://user-images.githubusercontent.com/61388609/76153034-c0a43700-60c6-11ea-916a-80c60cbbfe4a.jpeg)
底色可以换成欧盟蓝XD

**Comment by cmp0xff** [comment]
![grafik](https://user-images.githubusercontent.com/5564164/76576835-9fc35380-64c3-11ea-9df4-c4b3e8d9fc58.png)
https://www.der-postillon.com/2020/03/louvre-coronavirus.html

**Comment by cyannn** [comment]
![45D32089-A97D-4797-B811-2300BABCB782](https://user-images.githubusercontent.com/10817593/76576875-b9649b00-64c3-11ea-9a13-bc78fbb221a8.jpeg)

**Comment by Ulyssssss** [comment]
@cyannn

**Comment by Ulyssssss** [comment]
@cyannn

**Comment by Ulyssssss** [comment]
@cyannn

**Comment by Ulyssssss** [comment]
@cyannn

**Comment by Ulyssssss** [comment]
![image](https://user-images.githubusercontent.com/61524479/76578418-cd5ecb80-64c8-11ea-9840-bb41d5f7b7c6.png)
![image](https://user-images.githubusercontent.com/61524479/76578431-db145100-64c8-11ea-9680-57e389689084.png)
![image](https://user-images.githubusercontent.com/61524479/76578436-e4052280-64c8-11ea-8637-d5f56b0b05a1.png)

脸上加口罩
