### ISSUE TITLE
德国Tagesschau

### ISSUE THREAD

**Issue by AliceZhao121** [covid19-eu-zh/docs#35]
德国Tagesschau
德国总理Angela Merkel （基民盟）今日结束德国与各州长电话举行的危机峰会直播，规定全德禁止2人以上非一户的各种形式、地点的聚会。所有仍在经营的餐厅酒店等非生存必须产业从明日起关门歇业，虽未强制企业改变员工工作方式及场所，但未实行home office的员工必须提供相应保护措施。

Merkel表示以上决定将至少持续两周，虽然不能见到远方的家人，但现阶段不见面才是真爱。然而这种暂时的“出行限制”并不是强制的。尴尬的是在电话会议上，梅前州与黑森州州长职责巴伐利亚与萨尔州提前行动，擅自宣布严格实施政府呼吁的保护措施“限制出行”，而巴伐利亚与萨尔州州长则反扑其他各州采取措施过晚。

**Comment by cmp0xff** [comment]
@AliceZhao121 得給鏈結

**Comment by cmp0xff** [comment]
這個要不再整理一下？

首先是干货部分比较简略。这种具体规定应该能从卫生部等政府网站上挖到正式文件。给出链接。

其次是『相互指責』部分感觉比较八卦。按照我们之前的风格，我觉得得至少有两家媒体互相印证才行，不至于沦为八卦小报。

**Comment by AliceZhao121** [comment]
🇩🇪德国进入"限制出行"阶段
德国总理Angela Merkel 於3月22日 在#聯邦衛生部 發表演講 (https://www.bundesregierung.de/breg-de/themen/coronavirus/bund-laender-leitlinien-1733222)
德国总理Angela Merkel （基民盟CDU）22日与德國各州长电话举行的危机峰会直播就新冠問題發表決議，聯邦政府將擴大限制社會交際的措施，规定全德禁止2人以上非一户的各种形式、地点的聚会。違反交際限令的行為將受到有關部門的監控視情節輕重予以處罰。所有仍在经营的餐厅酒店等非生存必须产业从明日起关门歇业，外賣、取餐與醫療服務業務除外。虽未强制企业改变员工工作方式及场所，但未实行home office的员工必须提供相应保护措施。
Merkel表示以上决定将至少持续两周，虽然不能见到远方的家人，但现阶段不见面才是安全保護自己保護家人的措施。

德國#Focus 報導 (https://www.focus.de/finanzen/recht/ausgangssperre-was-verboten-und-was-erlaubt-ist-und-welche-strafen-es-gibt_id_11793149.html)了各州針對此次連線分別做出的決議措施

编辑：Katzenkuerbis
#德国 #德國 #Deutschland #疫情動態 #防疫资讯
