### ISSUE TITLE
需要关注 Robert Koch 的动向

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/docs#6]
需要一个德语使用者来关注 [Robert Koch 研究所](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html)的动向。由于我转去写文档了，难以兼顾。

其中 Aktuelle Risikobewertung des RKI für Deutschland 每两天都更新，且覆盖之前的结果。可以使用 https://t.me/CorsaBot 来**简便保存历史版本**。目前的关注成果是，[2 月 24 日](https://t.me/covid19_eu_zh_c/167) COVID 的风险是**低**，而 [2 月 26 日](https://t.me/covid19_eu_zh_c/180)的风险已经调高到了低至中等。

Fallzahlen 似乎是每天上午更新。

**Comment by prplchry** [comment]
@cmp0xff 我關注一下，如果變動不大，就可能參考你之前的翻譯，小改。

**Comment by cmp0xff** [comment]
@prplchry 感謝，因為會覆蓋舊文，所以存檔之後，比較好比較原文。可以只更新區別部分，不用每次都全文翻譯。今天我看風險仍是中低。

**Comment by prplchry** [comment]
2月28日較2月26的前版幾乎無變動，存檔在：https://telegra.ph/RKI-2%E6%9C%8828%E6%97%A5%E9%87%9D%E5%B0%8DCOVID-19%E7%9A%84%E9%A2%A8%E9%9A%AA%E8%A9%95%E4%BC%B0-02-28。
3月1日需關注更新。

**Comment by cmp0xff** [comment]
> 2月28日較2月26的前版幾乎無變動，存檔在：https://telegra.ph/RKI-2%E6%9C%8828%E6%97%A5%E9%87%9D%E5%B0%8DCOVID-19%E7%9A%84%E9%A2%A8%E9%9A%AA%E8%A9%95%E4%BC%B0-02-28。
> 3月1日需關注更新。

感谢！哎这边有些人名字跟 Telegram 里不一样，令我晕眩。

另外就是希望给**原文**存档。译文比较随意，比较价值不很大。

还有就是上面你写的链接不能直接点进去。不过也很好解决就是了😀
