### ISSUE TITLE
需要德语区每日疫情通报，以及发布之前总结的传染链

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/docs#8]
现在德语区每日疫情通报好像没有人做了。需要考虑一下详细到什么程度。是每个省级行政单位吗。

另外之前总结在 Google Sheets 里面的传染链也应该发布出来。

我觉得传染链做不下去了。工作量过大，适合专业编辑。

**Comment by prplchry** [comment]
@cmp0xff @optikpapier 你的進度如何？

**Comment by cmp0xff** [comment]
@prplchry 我看到是刚刚完成了之前的传播链研究。但是没有想好怎么发出去。

**Comment by cmp0xff** [comment]
烷……我觉得德语区缺一个总结的人。

德语区明天再做吧，今天没法弄了。
