### ISSUE TITLE
关于微博上的抄袭问题

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/docs#9]
X 提到有人疑似在微博上搬运和整理我们的内容

![grafik](https://user-images.githubusercontent.com/5564164/75547852-268c2100-5a2c-11ea-8bcd-d6e7a6f12112.png)
和[这条](https://t.me/covid19_eu_zh_c/211)很像

optikpapier 提到我们可以自己开微博

wxfbeing 提到需要额外人力，且会审查

@cmpxff 提到可以用 [IFTTT](https://ifttt.com/applets/gHh84Wyb-rss-to-sina-weibo) 自动运营

**Comment by wxfbeing** [comment]
@cmp0xff 不仅是“审查”，编辑如已知在编写的内容会发送到微博平台的前提下，可能在写稿及编译时出现“自我审查”，如表述转写等。希望大家尽可能实践表达自由。

**Comment by cmp0xff** [comment]
@wxfbeing 可以忽略掉风险，只是简单推送，炸了就换下一个。不过无法保证账号实名持有者的绝对安全。
